const Countries =[
    {
        "id":"0",
        "country":"Armenia"
    },
    {
        "id":"1",
        "country":"Australia"
    },
    {
        "id":"2",
        "country":"Austria"
    },
    {
        "id":"3",
        "country":"Azerbaijan"
    },
    {
        "id":"4",
        "country":"Bahamas"
    },
    {
        "id":"5",
        "country":"Bahrain"
    },
    {
        "id":"6",
        "country":"Belarus"
    },
    {
        "id":"7",
        "country":"Belgium"
    },
    {
        "id":"8",
        "country":"Bermuda"
    },
    {
        "id":"9",
        "country":"Brazil"
    },
    {
        "id":"10",
        "country":"Bulgaria"
    },
    {
        "id":"11",
        "country":"Burkina Faso"
    },
    {
        "id":"12",
        "country":"Canada"
    },
    {
        "id":"13",
        "country":"Chinese Taipei"
    },
    {
        "id":"14",
        "country":"Colombia"
    },
    {
        "id":"15",
        "country":"Croatia"
    },
    {
        "id":"16",
        "country":"Cuba"
    },
    {
        "id":"17",
        "country":"Czech Republic"
    },
    {
        "id":"18",
        "country":"Côte d'Ivoire"
    },
    {
        "id":"19",
        "country":"Denmark"
    },
    {
        "id":"20",
        "country":"Dominican Republic"
    },
    {
        "id":"21",
        "country":"Ecuador"
    },
    {
        "id":"22",
        "country":"Egypt"
    },
    {
        "id":"23",
        "country":"Estonia"
    },
    {
        "id":"24",
        "country":"Ethiopia"
    },
    {
        "id":"25",
        "country":"Finland"
    },
    {
        "id":"26",
        "country":"France"
    },
    {
        "id":"27",
        "country":"Georgia"
    },
    {
        "id":"28",
        "country":"Germany"
    },
    {
        "id":"29",
        "country":"Ghana"
    },
    {
        "id":"30",
        "country":"Great Britain"
    },
    {
        "id":"31",
        "country":"Greece"
    },
    {
        "id":"32",
        "country":"Grenada"
    },
    {
        "id":"33",
        "country":"Hong Kong, China"
    },
    {
        "id":"34",
        "country":"Hungary"
    },
    {
        "id":"35",
        "country":"India"
    },
    {
        "id":"36",
        "country":"Indonesia"
    },
    {
        "id":"37",
        "country":"Ireland"
    },
    {
        "id":"38",
        "country":"Islamic Republic of Iran"
    },
    {
        "id":"39",
        "country":"Israel"
    },
    {
        "id":"40",
        "country":"Italy"
    },
    {
        "id":"41",
        "country":"Jamaica"
    },
    {
        "id":"42",
        "country":"Japan"
    },
    {
        "id":"43",
        "country":"Jordan"
    },
    {
        "id":"44",
        "country":"Kazakhstan"
    },
    {
        "id":"45",
        "country":"Kenya"
    },
    {
        "id":"46",
        "country":"Kosovo"
    },
    {
        "id":"47",
        "country":"Kuwait"
    },
    {
        "id":"48",
        "country":"Kyrgyzstan"
    },
    {
        "id":"49",
        "country":"Latvia"
    },
    {
        "id":"50",
        "country":"Lithuania"
    },
    {
        "id":"51",
        "country":"Malaysia"
    },
    {
        "id":"52",
        "country":"Mexico"
    },
    {
        "id":"53",
        "country":"Mongolia"
    },
    {
        "id":"54",
        "country":"Morocco"
    },
    {
        "id":"55",
        "country":"Namibia"
    },
    {
        "id":"56",
        "country":"Netherlands"
    },
    {
        "id":"57",
        "country":"New Zealand"
    },
    {
        "id":"58",
        "country":"Nigeria"
    },
    {
        "id":"59",
        "country":"North Macedonia"
    },
    {
        "id":"60",
        "country":"Norway"
    },
    {
        "id":"61",
        "country":"People's Republic of China"
    },
    {
        "id":"62",
        "country":"Philippines"
    },
    {
        "id":"63",
        "country":"Poland"
    },
    {
        "id":"64",
        "country":"Portugal"
    },
    {
        "id":"65",
        "country":"Puerto Rico"
    },
    {
        "id":"66",
        "country":"Qatar"
    },
    {
        "id":"67",
        "country":"Republic of Korea"
    },
    {
        "id":"68",
        "country":"ROC"
    },
    {
        "id":"69",
        "country":"Romania"
    },
    {
        "id":"70",
        "country":"San Marino"
    },
    {
        "id":"71",
        "country":"Saudi Arabia"
    },
    {
        "id":"72",
        "country":"Serbia"
    },
    {
        "id":"73",
        "country":"Slovakia"
    },
    {
        "id":"74",
        "country":"South Africa"
    },
    {
        "id":"75",
        "country":"Spain"
    },
    {
        "id":"76",
        "country":"Sweden"
    },
    {
        "id":"77",
        "country":"Switzerland"
    },
    {
        "id":"78",
        "country":"Syrian Arab Republic"
    },
    {
        "id":"79",
        "country":"Thailand"
    },
    {
        "id":"80",
        "country":"Tunisia"
    },
    {
        "id":"81",
        "country":"Turkey"
    },
    {
        "id":"82",
        "country":"Turkmenistan"
    },
    {
        "id":"83",
        "country":"Uganda"
    },
    {
        "id":"84",
        "country":"Ukraine"
    },
    {
        "id":"85",
        "country":"United States of America"
    },
    {
        "id":"86",
        "country":"Uzbekistan"
    },
    {
        "id":"87",
        "country":"Venezuela"
    }
]
export default Countries